module.exports = [

    'bower_components/jquery/dist/jquery.min.js',
    'backend/js/adminbagdemo.js',
    'bower_components/jStorage/jstorage.js',
    'bower_components/jquery-ui/jquery-ui.js',
    'bower_components/flexslider/jquery.flexslider-min.js',
    'bower_components/bootstrap-sass/assets/javascripts/bootstrap.min.js',
    'bower_components/fancyBox/source/jquery.fancybox.js',
    'bower_components/peity/jquery.peity.min.js',
    'bower_components/jquery-slimscroll/jquery.slimscroll.min.js',
    // *****************************************************************************************************
    "bower_components/Flot/jquery.flot.js",
    "bower_components/Flot/jquery.flot.categories.js",
    "bower_components/Flot/jquery.flot.pie.js",
    "bower_components/Flot/jquery.flot.resize.js",
    "bower_components/Flot/jquery.flot.time.js",
    "bower_components/Flot/jquery.flot.symbol.js",
    // *****************************************************************************************************

    '../../js/tinymce/tinymce.js',
    '../../js/tinymce/themes/modern/theme.js',
    'bower_components/angular/angular.min.js',
    "bower_components/angular-flot/angular-flot.js",
    'bower_components/angular-animate/angular-animate.min.js',
    'bower_components/angular-flexslider/angular-flexslider.js',
    'bower_components/angular-ui-select/dist/select.min.js',
    'bower_components/angular-sanitize/angular-sanitize.min.js',
    'bower_components/angular-ui-router/release/angular-ui-router.min.js',
    'bower_components/angular-bootstrap/ui-bootstrap.min.js',
    'bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js',
    'bower_components/angular-flexslider/angular-flexslider.js',
    'bower_components/angular-translate/angular-translate.js',
    'bower_components/lodash/lodash.js',
    'bower_components/angulartics/dist/angulartics.min.js',
    'bower_components/angulartics-google-analytics/dist/angulartics-ga.min.js',
    'bower_components/angular-ui-tinymce/src/tinymce.js',
    'bower_components/angularjs-imageupload-directive/public/javascripts/imageupload.js',
    'bower_components/ngmap/build/scripts/ng-map.min.js',
    "bower_components/angular-bootstrap-toggle-switch/angular-toggle-switch.min.js",
    "bower_components/angular-toastr/dist/angular-toastr.js",
    "bower_components/angular-toastr/dist/angular-toastr.tpls.js",
    "bower_components/angular-hotkeys/build/hotkeys.js",
    "bower_components/moment/min/moment.min.js",
    "bower_components/angular-ui-sortable/sortable.js",
    "bower_components/intl-tel-input/lib/libphonenumber/build/utils.js",
    "bower_components/intl-tel-input/build/js/intlTelInput.js",

    "bower_components/international-phone-number/releases/international-phone-number.js",
    "bower_components/angular-ui-select/dist/select.js",
    // "bower_components/angular-mapboxgl-directive/dist/angular-mapboxgl-directive.js",
    // "bower_components/raphael/raphael.min.js",
    // "bower_components/angular-flot/angular-flot.js",
    // *******my bower component********
    // "bower_components/angular-morris/build/module/angular-morris/angular-morris.js",
    // *******my bower component********

    // "bower_components/highcharts-ng/dist/highcharts-ng.js",
    "bower_components/mapbox.js/mapbox.js",
    "node_modules/mapbox-gl-draw/dist/mapbox-gl-draw.js",
    "node_modules/@turf/turf/turf.min.js",
    "node_modules/leaflet-draw/dist/leaflet.draw.js",
    "node_modules/async/dist/async.js",
    // "bower_components/crypto-js/hmac.js",
    // "bower_components/crypto-js/cre.js",
    // "bower_components/crypto-js/md5.js",
    // "bower_components/crypto-js/sha256.js",
    // "bower_components/crypto-js/sha1.js",
    // 'backend/js/plugins/flot/jquery.flot.js',
    // 'backend/js/plugins/flot/jquery.flot.pie.js',
    // 'backend/js/plugins/flot/jquery.flot.resize.js',
    // 'backend/js/plugins/flot/jquery.flot.spline.js',
    // 'backend/js/plugins/flot/jquery.flot.time.js',
    // 'backend/js/plugins/flot/jquery.flot.tooltip.min.js',


    'backend/js/app.js',
    'backend/js/language.js',
    'backend/js/controllers.js',
    'backend/js/navigation.js',
    'backend/js/templateservice.js',
    'backend/js/jsonService.js',
    'backend/sass/plugins/chartJs/angles.js',
    'backend/sass/plugins/chartJs/Chart.min.js',
    'backend/js/adminbox.js',
    // 'backend/js/plugins/flot/angular-flot.js',
    // 'backend/js/plugins/flot/curvedLines.js',
    'backend/js/plugins/summernote/summernote.min.js',
    'backend/js/plugins/summernote/angular-summernote.min.js',
    'backend/js/plugins/datapicker/angular-datepicker.js',
    // 'backend/js/plugins/amcharts/10/pie.js',
    // 'backend/js/plugins/amcharts/10/plugins/export/export.js',
    // 'backend/js/plugins/amcharts/10/radar.js',
    'backend/js/plugins/iCheck/icheck.min.js',
    'backend/js/plugins/ionRangeSlider/ion.rangeSlider.min.js',

    // 'backend/js/plugins/amcharts/plugins/export/libs/fabric.js/fabric.js',
    // 'backend/js/plugins/amcharts/plugins/export/libs/fabric.js/fabric.min.js',
    // 'backend/js/plugins/angular-morris/raphael-min.js',
    // 'backend/js/plugins/angular-morris/morris.min.js',
    // 'backend/js/plugins/angular-morris/angular-morris.min.js',


];